// Code generated by "esc -o template.go -pkg mkrest client.template"; DO NOT EDIT.

package mkrest

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/client.template": {
		local:   "client.template",
		size:    1902,
		modtime: 1550724679,
		compressed: `
H4sIAAAAAAAC/7RVX0/bPhR9jj/F/fUBJShyEW/8tE6CwsOmrWJF2x6RcW5ab6lTbGelCvnu07WdtIWO
h0njBef+v+ccu2shf4oFgqwUaseYWq1r4yBlyehh69COWDLS6MaNqegoa+3wyfXWpXNrOq+FW45LVSEd
yIBa1oXSi/EPW2syqHqs6sYpqtK2YIReIPAPvpuFrmPJqG2BQ9eFANQFWTPG3HaNYNCub4wB60wjHbQs
WdkFfSm9YIl1wjUWlHasY6xstITUDEkZ3Hl/mlEE5Rp0jdFgkIfM41k3xtQmzWKXw7yVXVDSeAxTDxxV
RlMKiWHel1bK3q39Gd2yLsLaZOYzsULoulS6J4gQ82n437agSuCXZkHxOVB4/BhgyiAl89yPZ6f1aiWg
65Dmz/bRDBPPcBPHC/vYOG2AYPCmoigMWhv3z0HCKfHNgzuDNBxyCI1oxXv/Af9PoDEVvxXGYl8mY4kq
vfe/CWhVUXgPqFaVT2RJ56MkTHYxEibg+15jKZrKxWEpNKafBPG2sVMOssspnfb1bAT/nngOV2OJhPC3
vyBlH6UsKEXCqYxA/GMGo3ZUCUOAV84vYbxYa20R9rK9c0d6jHts0LqrutiCv9f8qilLNH1l7j1ej5FA
urh8hpsbuslo0pO9EhkPVj8zGfr1M5YcYbnn6fiGLEkO5zX4OMjI8zHDzTw0T/0jEbigpyIHyQfWDyZ8
Q21/GiO0hgmBxb8rt4z8EaeZ9/Gv80/8VrglTKB/7fjHWul035mDn9LHdd0oY8ljg2ZL6/RhX8iQZvtv
ApkUBvJ8PL/DuG8EdxSk801UTcT6EDRfeS42vjhMIFSJTPkF7HoAVnLJr2ua+y+hKrDEoL+ggGlVW99G
lcEaHt1pXSC8g/OzM3h+fuV4D+cXF77hg7M53NNk4WeCz1EUl1WVDh2yN8eKr3YbbnT64GyWv2zXsai0
V1eJtt9J/hqD5HeteTDRJQj37SX4b6HVsSH0dwAAAP//h5+Es24HAAA=
`,
	},

	"/": {
		isDir: true,
		local: "",
	},
}
